import { type Category, h, note, p, see, steps, ul, warn } from "../../types";

export const troubleshoot: Category = {
  slug: "troubleshoot",
  title: "Fehler beheben",
  summary: "Die Dinge, die am häufigsten schiefgehen — und was Sie zuerst prüfen.",
  icon: "Wrench",
  sections: [
    {
      title: "Aufnahme und Upload",
      articles: [
        {
          slug: "photos-not-uploading",
          title: "Fotos werden nicht hochgeladen",
          summary: "Aufnahmen, die in der Warteschlange liegen — und wie Sie sie in Bewegung bringen.",
          keywords: [
            "upload",
            "warteschlange",
            "festgesteckt",
            "ausstehend",
            "offline",
            "synchronisieren",
            "grenze",
            "queue",
            "stuck",
            "pending",
            "sync",
            "limit",
          ],
          body: [
            p(
              "Aufnahmen bleiben auf dem Telefon, bis sie hochgeladen sind. Eine Warteschlange ist bei schlechtem Netz normal — eine, die sich nie leert, ist es nicht.",
            ),
            h("Prüfen Sie in dieser Reihenfolge"),
            steps(
              "Öffnen Sie die App und schauen Sie in die Upload-Warteschlange. Wenn dort Einträge warten, sind die Aufnahmen sicher auf dem Gerät.",
              "Sorgen Sie für echtes Netz oder Wi-Fi. Ein einzelner Balken verbindet oft, kann aber kein Foto bewegen.",
              "Holen Sie die App in den Vordergrund und lassen Sie sie dort eine Minute. Manche Telefone unterbrechen Übertragungen im Hintergrund sehr aggressiv.",
              "Prüfen Sie, dass das Telefon nicht im Energiespar- oder Datensparmodus ist — beide blockieren Uploads im Hintergrund.",
              "Melden Sie sich nur als letztes Mittel ab und wieder an — und tun Sie das, wenn die Warteschlange leer ist.",
            ),
            h("Wenn die Warteschlange sich leert, aber im Workspace nichts erscheint"),
            ul(
              "Prüfen Sie den Projektfilter in der Web-App. Die Aufnahmen sind vielleicht in einem Projekt gelandet, das Sie gerade nicht ansehen.",
              "Prüfen Sie den Datumsfilter. Eine Aufnahme aus der Warteschlange sortiert sich unter dem Tag ein, an dem sie gemacht wurde, nicht unter heute.",
              "Vergewissern Sie sich, dass Sie den richtigen Workspace ansehen, wenn Sie zu mehreren gehören.",
            ),
            h("Wenn Sie eine Monatsgrenze erreicht haben"),
            p(
              "Der Free-Plan deckt 300 Aufnahmen pro Monat ab. Darüber hinaus werden Uploads abgelehnt, bis der Monat wechselt oder Sie auf einen Plan ohne monatliche Obergrenze wechseln.",
            ),
            warn(
              "Löschen Sie die App nicht, solange Aufnahmen in der Warteschlange stehen. Hochgeladene Aufnahmen liegen in Ihrem Workspace, aber alles, was noch auf dem Gerät wartet, geht mit ihr verloren.",
            ),
            note(
              "Die Aufnahmezeit wird auf dem Gerät festgehalten. Ein Foto, das zwei Tage später hochlädt, trägt also weiterhin den Moment, in dem ausgelöst wurde — und die Verifizierung gibt das so wieder.",
            ),
            see("mobile-app/offline-capture-and-queue", "plans-billing/compare-plans"),
          ],
        },
        {
          slug: "gps-or-address-wrong",
          title: "Die GPS-Position oder die Adresse ist falsch",
          summary: "Warum ein Pin abdriftet und was Sie bei einem falschen Straßennamen tun.",
          keywords: [
            "gps",
            "standort",
            "adresse",
            "genauigkeit",
            "falsch",
            "abweichung",
            "berechtigung",
            "location",
            "address",
            "accuracy",
            "wrong",
            "drift",
            "permission",
          ],
          body: [
            p(
              "GeoCliks hält die Position fest, die das Telefon meldet, und löst diese Position dann zu einer Straßenadresse auf. Beide Schritte können abweichen, aus unterschiedlichen Gründen.",
            ),
            h("Der Pin sitzt an der falschen Stelle"),
            ul(
              "In Gebäuden, im Keller, im Parkhaus oder zwischen hohen Häusern ist der Satellitenempfang schlecht, und das Telefon fällt auf eine gröbere Ortung zurück.",
              "Ein Telefon, das gerade eingeschaltet wurde, hat noch keine Ortung. Geben Sie ihm vor der ersten Aufnahme des Tages fünfzehn Sekunden im Freien.",
              "Jede Aufnahme hält ihre Genauigkeit fest. Ein großer Genauigkeitswert ist das Telefon, das Ihnen sagt, dass es unsicher war — das ist eine Funktion, kein Fehler.",
            ),
            h("Die Position stimmt, aber die Adresse ist falsch"),
            p(
              "Die Adresse wird aus den Koordinaten nachgeschlagen. In einem Neubaugebiet, an einer Landstraße oder auf einem großen Gelände mit einer einzigen Hausnummer kommt die nächstbekannte Adresse zurück, und das kann ein Nachbargebäude sein. Maßgeblich bleiben die Koordinaten.",
            ),
            h("Es gibt überhaupt keinen Standort"),
            steps(
              "Öffnen Sie die Einstellungen Ihres Telefons und suchen Sie GeoCliks.",
              "Setzen Sie die Standortberechtigung auf „Beim Verwenden der App“ oder „Immer“.",
              "Schalten Sie auf dem iPhone außerdem „Genauer Standort“ ein. Ohne das erhalten Sie eine grobe Gegend statt einer Position.",
              "Nehmen Sie erneut auf. Früheren Aufnahmen kann nachträglich kein Standort gegeben werden.",
            ),
            h("Lieferstopps an der falschen Stelle"),
            p(
              "Die Position eines Stopps entsteht aus dem Auflösen der eingegebenen Adresse, nicht aus einem Telefon. Korrigieren Sie die Adresse und lösen Sie erneut auf, oder setzen Sie den Pin von Hand.",
            ),
            warn(
              "Eine Position kann nach der Aufnahme nicht hinzugefügt oder bearbeitet werden. Genau das macht sie zum Nachweis — ließe sie sich später korrigieren, würde sie nichts beweisen.",
            ),
            see("delivery-routes/geocoding-and-fixing-addresses", "verify/verify-results-explained"),
          ],
        },
      ],
    },
    {
      title: "Zugang",
      articles: [
        {
          slug: "cant-sign-in",
          title: "Anmeldung nicht möglich",
          summary: "Falsches Passwort, nicht bestätigte E-Mail oder die falsche Anmeldemethode.",
          keywords: [
            "anmelden",
            "anmeldung",
            "passwort",
            "zurücksetzen",
            "bestätigen",
            "gesperrt",
            "sign in",
            "login",
            "password",
            "reset",
            "verify",
            "google",
            "locked",
          ],
          body: [
            p(
              "Arbeiten Sie das der Reihe nach durch — die Ursache ist meist eine der ersten drei.",
            ),
            h("Die Grundlagen prüfen"),
            steps(
              "Bestätigen Sie die E-Mail-Adresse. Eine dienstliche und eine private Adresse sind zwei verschiedene Konten.",
              "Nutzen Sie dieselbe Methode, mit der Sie sich registriert haben. Ein mit Google erstelltes Konto hat kein Passwort zum Eintippen.",
              "Setzen Sie Ihr Passwort über den Anmeldebildschirm zurück, wenn Sie unsicher sind.",
              "Öffnen Sie die Bestätigungs-E-Mail, wenn Sie die Adresse nie bestätigt haben — ein unbestätigtes Konto kann sich nicht anmelden.",
            ),
            h("Es kommt nichts an, wenn Sie ein Zurücksetzen anfordern"),
            ul(
              "Prüfen Sie Spam- und Junk-Ordner.",
              "Warten Sie zwei Minuten. Wiederholte Anfragen können in eine Ratenbegrenzung laufen, was die Sache weiter verlangsamt.",
              "Vergewissern Sie sich, dass die Adresse existiert — ein Zurücksetzen für eine Adresse ohne Konto verschickt nichts.",
            ),
            h("Sie sollen nachweisen, dass Sie ein Mensch sind"),
            p(
              "Wiederholte Fehlversuche können eine Prüfung auslösen. Schließen Sie sie ab und machen Sie weiter. Wenn sie immer wieder erscheint, versuchen Sie ein normales Browserfenster statt eines privaten und schalten Sie Erweiterungen aus, die Skripte blockieren.",
            ),
            h("Sie melden sich an, landen aber am falschen Ort"),
            ul(
              "Wenn Sie zu mehr als einem Workspace gehören, wechseln Sie den Workspace über das Kontomenü.",
              "Ein Feld-Mitglied sieht nur die ihm zugewiesenen Projekte. Ein leer wirkender Workspace bedeutet also meist, dass es noch keine Projektzuweisungen gibt — fragen Sie einen Admin.",
            ),
            note(
              "Aus einem Workspace entfernt zu werden löscht Ihr Konto nicht. Sie können sich weiterhin anmelden, Sie sehen diesen Workspace nur nicht mehr.",
            ),
            see("troubleshoot/two-factor-issues", "getting-started/create-your-account"),
          ],
        },
        {
          slug: "two-factor-issues",
          title: "Probleme mit der Zwei-Faktor-Anmeldung",
          summary: "Abgelehnte Codes, ein verlorenes Telefon und wie Backup-Codes funktionieren.",
          keywords: [
            "2fa",
            "zwei faktor",
            "totp",
            "authenticator",
            "backup-codes",
            "code abgelehnt",
            "two factor",
            "backup codes",
            "code rejected",
          ],
          body: [
            p(
              "Die Zwei-Faktor-Anmeldung ist optional und wird Inhabern und Admins auf ihrer Profilseite angeboten. Feld-Teams werden absichtlich nicht durch eine Authenticator-App geschleust, weil ein gemeinsam genutztes Fahrzeugtelefon das zur Qual macht.",
            ),
            h("Der Code wird abgelehnt"),
            steps(
              "Prüfen Sie, dass Sie den GeoCliks-Eintrag in Ihrer Authenticator-App ablesen und nicht einen anderen Dienst.",
              "Warten Sie auf den nächsten Code. Codes wechseln alle 30 Sekunden, und einer, der kurz vor dem Ablauf steht, wird oft abgewiesen.",
              "Tippen Sie alle sechs Ziffern ohne Leerzeichen.",
              "Prüfen Sie, dass die Uhr des Telefons automatisch gestellt wird. Eine Geräteuhr, die mehrere Minuten falsch läuft, erzeugt Codes, die der Server nicht annimmt.",
            ),
            h("Sie haben das Telefon mit dem Authenticator verloren"),
            p(
              "Nutzen Sie einen der Backup-Codes, die Sie beim Einschalten der Zwei-Faktor-Anmeldung erhalten haben. Wählen Sie im Bildschirm des zweiten Schritts die Backup-Code-Option und geben Sie einen ein. Jeder Code funktioniert einmal.",
            ),
            warn(
              "Wenn Sie sowohl den Authenticator als auch die Backup-Codes verloren haben, können wir das Konto nicht über den Anmeldebildschirm wiederherstellen. Schreiben Sie von der eigenen Adresse des Kontos an support@geocliks.com und rechnen Sie mit Identitätsprüfungen — diese Hürde ist der Sinn der Zwei-Faktor-Anmeldung.",
            ),
            h("Sie abschalten"),
            p(
              "Melden Sie sich an, öffnen Sie Ihr Profil und deaktivieren Sie die Zwei-Faktor-Anmeldung. Sie werden um eine Bestätigung gebeten. Wenn Sie der Inhaber sind, lassen Sie sie besser an — das ist das Konto, das die Abrechnung ändern und Personen entfernen kann.",
            ),
            note(
              "Die Zwei-Faktor-Anmeldung gilt überall für Ihr Konto. Sobald sie an ist, fragen sowohl die Website als auch die Telefon-App nach dem zweiten Schritt.",
            ),
            see("troubleshoot/cant-sign-in", "teamspace/roles-and-permissions"),
          ],
        },
        {
          slug: "invite-not-working",
          title: "Eine Einladung funktioniert nicht",
          summary: "Keine E-Mail, ein abgelaufener Link oder keine Plätze mehr im Plan.",
          keywords: [
            "einladung",
            "einladen",
            "platz",
            "abgelaufen",
            "annehmen",
            "qr",
            "invite",
            "invitation",
            "seat",
            "expired",
            "accept",
            "email",
          ],
          body: [
            p(
              "Probleme mit Einladungen laufen auf die Adresse, die Plätze oder den Plan hinaus.",
            ),
            h("Die E-Mail ist nie angekommen"),
            steps(
              "Öffnen Sie „Team“ und prüfen Sie die Liste der offenen Einladungen — steht die Einladung dort, wurde sie erstellt.",
              "Prüfen Sie die Adresse auf einen Tippfehler. Eine Einladung ist an genau die Adresse gebunden, an die sie geschickt wurde.",
              "Lassen Sie die Person im Spam nachsehen.",
              "Nutzen Sie stattdessen den QR-Code: offene Einladung öffnen, Code zeigen und von der Person mit dem Telefon scannen lassen.",
            ),
            h("Sie haben angenommen, sehen aber nichts"),
            p(
              "Feld-Mitglieder sehen nur Projekte, denen sie zugewiesen sind. Weisen Sie sie über „Team“ oder direkt im Projekt zu, dann erscheint es innerhalb von Augenblicken auf ihrem Telefon.",
            ),
            h("Sie können die Einladung überhaupt nicht senden"),
            ul(
              "Keine Plätze mehr frei: offene Einladungen belegen ebenfalls einen Platz. Ziehen Sie alte Einladungen zurück, entfernen Sie Personen, die gegangen sind, oder wechseln Sie auf einen größeren Plan.",
              "Teamspace nicht enthalten: Einladungen beginnen mit dem Business-Plan. Free und Plus haben einen einzelnen Platz.",
              "Falsche Rolle: Einladen setzt Admin oder Inhaber voraus.",
            ),
            h("Sie haben mit einer anderen E-Mail angenommen"),
            p(
              "Das funktioniert nicht — die Einladung passt nur zu der Adresse, an die sie geschickt wurde. Ziehen Sie sie zurück und schicken Sie eine neue an die Adresse, die die Person tatsächlich nutzt.",
            ),
            note("Eine offene Einladung zurückzuziehen gibt ihren Platz sofort frei."),
            see("teamspace/invite-your-crew", "plans-billing/seats-and-billing"),
          ],
        },
      ],
    },
    {
      title: "Touren, Exporte und Hinweise",
      articles: [
        {
          slug: "route-optimize-failed",
          title: "Eine Tour lässt sich nicht optimieren",
          summary: "Meist nicht aufgelöste Adressen. Manchmal der Plan.",
          keywords: [
            "optimieren",
            "tour",
            "fehlgeschlagen",
            "koordinaten",
            "geokodierung",
            "reihenfolge",
            "optimize",
            "route",
            "failed",
            "coordinates",
            "geocode",
            "order",
          ],
          body: [
            p("Die Optimierung arbeitet mit Kartenpositionen, nicht mit eingegebenen Adressen."),
            h("„Noch kein Stopp hat Koordinaten“"),
            steps(
              "Öffnen Sie die Tour und wählen Sie „Adressen auflösen“.",
              "Sehen Sie sich die Stopps an, die sich nicht auflösen ließen.",
              "Korrigieren Sie den Adresstext oder setzen Sie den Pin von Hand auf der Karte.",
              "Optimieren Sie erneut.",
            ),
            h("Es wurde optimiert, aber einige Stopps hängen am Ende"),
            p(
              "Stopps ohne Position können nicht einsortiert werden und werden daher am Ende der Liste geparkt, statt aus der Tour zu fallen. Lösen Sie sie auf oder setzen Sie einen Pin und optimieren Sie erneut.",
            ),
            h("Sie haben die intelligente Optimierung angefordert und die Standardoptimierung bekommen"),
            p(
              "In einem Plan ohne die intelligente Optimierung führt GeoCliks die Standardoptimierung aus statt abzulehnen. Sie erhalten trotzdem eine sortierte Tour. Die Historie der Tour hält fest, welche Optimierung gelaufen ist.",
            ),
            h("Die Reihenfolge sieht Ihnen weiterhin falsch aus"),
            ul(
              "Prüfen Sie, dass die Startadresse gesetzt ist — und ob die Rückkehr zum Start eingeschaltet sein sollte.",
              "Prüfen Sie die Servicezeit — ein völlig falscher Wert verzerrt jede Ankunftsschätzung.",
              "Zeitfenster an Stopps schränken die Reihenfolge ein, und ein enges Fenster setzt sich gegen den kürzesten Weg durch.",
              "Ziehen Sie Stopps von Hand. Ortskenntnis schlägt einen Algorithmus häufiger, als Anbieter zugeben.",
            ),
            see("delivery-routes/optimize-stop-order", "delivery-routes/geocoding-and-fixing-addresses"),
          ],
        },
        {
          slug: "export-or-report-failed",
          title: "Ein Export oder Bericht ist fehlgeschlagen",
          summary: "Plangrenzen, zu große Auswahlen und Formate, die nicht enthalten sind.",
          keywords: [
            "export",
            "bericht",
            "pdf",
            "excel",
            "zip",
            "kmz",
            "fehlgeschlagen",
            "herunterladen",
            "report",
            "failed",
            "download",
          ],
          body: [
            p("Die meisten fehlgeschlagenen Exporte sind eine Plangrenze und kein Fehler."),
            h("Das Format ist nicht verfügbar"),
            ul(
              "Der Free-Plan erzeugt nur ein PDF, mit bis zu 20 Fotos.",
              "Excel, ZIP und KMZ beginnen mit Plus.",
              "Sie erfahren es, bevor die Datei gebaut wird, und nicht danach — es wird also nichts halb erzeugt.",
            ),
            h("Der Export ist sehr groß"),
            steps(
              "Grenzen Sie die Auswahl mit dem Datums- oder Projektfilter ein.",
              "Exportieren Sie in Paketen — ein Monat auf einmal ist leichter zu verschicken und auch leichter zu bauen.",
              "Bei tausenden Originalen nehmen Sie besser ZIP als PDF. Ein PDF dieser Größe ist ohnehin unbrauchbar.",
            ),
            h("Die Datei lädt nie herunter"),
            ul(
              "Berichte werden auf dem Server gebaut und dann in Ihrer Berichtsliste aufgeführt — schauen Sie dort und laden Sie ihn erneut herunter, statt ihn neu zu bauen.",
              "Prüfen Sie, dass der Browser den Download nicht blockiert hat, und schauen Sie in Ihrem Download-Ordner.",
              "Probieren Sie einmal einen anderen Browser, bevor Sie es melden.",
            ),
            h("Ein KMZ lässt sich nicht öffnen"),
            p(
              "KMZ braucht Google Earth oder GIS-Software. Es ist kein Dokumentformat und öffnet sich nicht in einem PDF-Leser oder einer Tabellenkalkulation.",
            ),
            note(
              "Jeder erzeugte Bericht bleibt in Ihrer Berichtsliste, Sie können ihn also später erneut herunterladen, ohne ihn neu zu bauen.",
            ),
            see("teamspace/reports-and-exports", "plans-billing/compare-plans"),
          ],
        },
        {
          slug: "notifications-not-arriving",
          title: "Benachrichtigungen kommen nicht an",
          summary:
            "Push auf dem Telefon und die E-Mails, die Empfänger einer Lieferung bekommen sollten.",
          keywords: [
            "benachrichtigungen",
            "push",
            "e-mail",
            "hinweise",
            "stumm",
            "empfänger",
            "sendungsverfolgung",
            "notifications",
            "email",
            "alerts",
            "silent",
            "recipient",
            "tracking",
          ],
          body: [
            p(
              "Zwei verschiedene Systeme — prüfen Sie also das, das zu dem passt, was fehlt.",
            ),
            h("Push-Benachrichtigungen auf dem Telefon"),
            steps(
              "Öffnen Sie die Einstellungen Ihres Telefons, suchen Sie GeoCliks und erlauben Sie Benachrichtigungen.",
              "Prüfen Sie „Nicht stören“, Fokus-Modi und jeden Nachtzeitplan.",
              "Öffnen Sie die App einmal, während Sie angemeldet sind — das Gerät registriert sich bei der Anmeldung für Push, ein Telefon, das seit einer Neuinstallation die App nicht geöffnet hat, ist also nicht registriert.",
              "Schicken Sie sich zum Testen aus der Web-App eine Nachricht.",
            ),
            h("Ein Teammitglied bekommt nichts"),
            ul(
              "Die Person muss Mitglied des Workspace und auf diesem Gerät angemeldet sein.",
              "Rundnachrichten gehen an die Kontakte des Workspace — wer aus dem Workspace entfernt wurde, erhält sie nicht mehr.",
              "Ein Telefon, das tagelang offline war, erhält wartende Benachrichtigungen beim Wiederverbinden — oder gar nicht, wenn sie abgelaufen sind.",
            ),
            h("Empfänger von Lieferungen bekommen keine E-Mails"),
            ul(
              "Der Stopp braucht eine E-Mail-Adresse des Empfängers. Ohne sie ist keine E-Mail möglich.",
              "Die Benachrichtigungseinstellungen der Tour selbst steuern die Vorankündigung und die E-Mails mit dem Zustellnachweis.",
              "Fehlgeschlagene Stopps senden nie eine E-Mail mit Zustellnachweis — so gewollt. Das Büro erledigt diese von Hand.",
              "Jeder Empfänger erhält jede E-Mail einmal, ein erneutes Senden geht also nicht zweimal hinaus.",
              "Der E-Mail-Versand muss für Ihren Workspace eingerichtet sein. Wenn noch nie ein Empfänger auf irgendeiner Tour etwas erhalten hat, ist das das Erste, was Sie prüfen sollten.",
            ),
            warn(
              "Bitten Sie den Empfänger, im Spam nachzusehen, bevor Sie schließen, dass nichts verschickt wurde. Transaktions-E-Mails mit einem Foto darin landen häufiger im Junk-Ordner, als man sich wünscht.",
            ),
            see("delivery-routes/tracking-links-and-notifications", "teamspace/messages-and-broadcasts"),
          ],
        },
      ],
    },
  ],
};
