// GENERATED by packages/web/scripts/gen-autumn-config.ts — edit plans in /admin/plans, then run
//   bun run autumn:config && bunx atmn push -y
import { feature, plan, item } from "atmn";

export const photos = feature({ id: "photos", name: "Photos", type: "metered", consumable: true });
export const teamspace = feature({ id: "teamspace", name: "Teamspace", type: "boolean" });
export const shareLinks = feature({ id: "share_links", name: "Share links", type: "boolean" });
export const branding = feature({ id: "branding", name: "Custom branding", type: "boolean" });
export const roles = feature({ id: "roles", name: "Role-based permissions", type: "boolean" });

export const free = plan({
  id: "free",
  name: "Free",
  items: [
    item({ featureId: photos.id, included: 300, reset: { interval: "month" } }),
  ],
});

export const plus = plan({
  id: "plus",
  name: "Plus",
  price: { amount: 7, interval: "month" },
  items: [
    item({ featureId: shareLinks.id }),
    item({ featureId: branding.id }),
  ],
});

export const business = plan({
  id: "business",
  name: "Business",
  price: { amount: 25, interval: "month" },
  items: [
    item({ featureId: teamspace.id }),
    item({ featureId: shareLinks.id }),
    item({ featureId: branding.id }),
    item({ featureId: roles.id }),
  ],
});

export const crew10 = plan({
  id: "crew10",
  name: "Crew 10",
  price: { amount: 45, interval: "month" },
  items: [
    item({ featureId: teamspace.id }),
    item({ featureId: shareLinks.id }),
    item({ featureId: branding.id }),
    item({ featureId: roles.id }),
  ],
});

export const crew25 = plan({
  id: "crew25",
  name: "Crew 25",
  price: { amount: 105, interval: "month" },
  items: [
    item({ featureId: teamspace.id }),
    item({ featureId: shareLinks.id }),
    item({ featureId: branding.id }),
    item({ featureId: roles.id }),
  ],
});

export const timeStamp = plan({
  id: "time_stamp",
  name: "Time Stamp (legacy)",
  items: [],
});

export default {
  features: [photos, teamspace, shareLinks, branding, roles],
  plans: [free, plus, business, crew10, crew25, timeStamp],
};
