import { type Category, h, note, p, see, steps, ul, warn } from "../../types";

export const troubleshoot: Category = {
  slug: "troubleshoot",
  title: "Khắc phục sự cố",
  summary: "Những thứ hay hỏng nhất, và nên kiểm tra gì trước.",
  icon: "Wrench",
  sections: [
    {
      title: "Chụp và tải lên",
      articles: [
        {
          slug: "photos-not-uploading",
          title: "Ảnh không tải lên được",
          summary: "Ảnh chụp nằm lại trong hàng chờ, và cách làm chúng chạy tiếp.",
          keywords: [
            "tải lên",
            "hàng chờ",
            "kẹt",
            "đang chờ",
            "ngoại tuyến",
            "đồng bộ",
            "giới hạn",
            "upload",
            "queue",
            "stuck",
            "pending",
            "offline",
            "sync",
            "limit",
          ],
          body: [
            p(
              "Ảnh chụp nằm lại trên điện thoại cho tới khi tải lên xong. Có hàng chờ khi sóng yếu là bình thường — một hàng chờ không bao giờ vơi thì không.",
            ),
            h("Kiểm tra theo thứ tự này"),
            steps(
              "Mở ứng dụng và xem hàng chờ tải lên. Nếu nó hiện các mục đang đợi, ảnh chụp vẫn an toàn trên thiết bị.",
              "Hãy tìm sóng thật hoặc Wi-Fi. Một vạch sóng thường kết nối được nhưng không đủ để chuyển một tấm ảnh.",
              "Đưa ứng dụng lên màn hình chính và để nguyên khoảng một phút. Một số điện thoại tạm dừng truyền dữ liệu nền rất gắt.",
              "Kiểm tra điện thoại không ở chế độ tiết kiệm pin hay tiết kiệm dữ liệu, vì chúng chặn tải lên ở nền.",
              "Chỉ đăng xuất rồi đăng nhập lại như biện pháp cuối cùng — và hãy làm khi hàng chờ đã rỗng.",
            ),
            h("Nếu hàng chờ vơi hết mà không có gì xuất hiện trong không gian làm việc"),
            ul(
              "Kiểm tra bộ lọc dự án trên ứng dụng web. Ảnh chụp có thể đã vào một dự án bạn không đang xem.",
              "Kiểm tra bộ lọc ngày. Một ảnh chụp trong hàng chờ được xếp vào ngày nó được chụp, không phải hôm nay.",
              "Xác nhận bạn đang xem đúng không gian làm việc nếu bạn thuộc nhiều nơi.",
            ),
            h("Nếu bạn đã chạm giới hạn hằng tháng"),
            p(
              "Gói Free bao gồm 300 lần chụp mỗi tháng. Vượt quá mức đó, việc tải lên bị từ chối cho tới khi sang tháng mới hoặc bạn chuyển sang một gói không giới hạn theo tháng.",
            ),
            warn(
              "Đừng xóa ứng dụng khi vẫn còn ảnh chụp trong hàng chờ. Ảnh đã tải lên nằm trong không gian làm việc của bạn, nhưng bất cứ thứ gì còn đợi trên thiết bị sẽ mất theo.",
            ),
            note(
              "Thời điểm chụp được ghi trên thiết bị, nên một tấm ảnh tải lên trễ hai ngày vẫn mang đúng khoảnh khắc bấm máy, và phần xác thực phản ánh điều đó.",
            ),
            see("mobile-app/offline-capture-and-queue", "plans-billing/compare-plans"),
          ],
        },
        {
          slug: "gps-or-address-wrong",
          title: "Vị trí GPS hoặc địa chỉ bị sai",
          summary: "Vì sao ghim bị lệch, và làm gì khi tên đường sai.",
          keywords: [
            "vị trí",
            "địa chỉ",
            "độ chính xác",
            "sai",
            "lệch",
            "quyền",
            "gps",
            "location",
            "address",
            "accuracy",
            "wrong",
            "drift",
            "permission",
          ],
          body: [
            p(
              "GeoCliks ghi lại vị trí mà điện thoại báo, rồi tra vị trí đó ra một địa chỉ đường phố. Cả hai bước đều có thể lệch, vì những lý do khác nhau.",
            ),
            h("Ghim nằm sai chỗ"),
            ul(
              "Trong nhà, dưới tầng hầm, trong bãi đỗ xe hay giữa các tòa nhà cao tầng, tín hiệu vệ tinh kém và điện thoại lùi về một phép định vị thô hơn.",
              "Một chiếc điện thoại vừa bật lên thì chưa có định vị. Hãy cho nó mười lăm giây ngoài trời trước lần chụp đầu tiên trong ngày.",
              "Mỗi ảnh chụp đều ghi lại độ chính xác của nó. Một con số sai lệch lớn là điện thoại đang nói với bạn rằng nó không chắc — đó là tính năng, không phải lỗi.",
            ),
            h("Vị trí đúng nhưng địa chỉ sai"),
            p(
              "Địa chỉ được tra ra từ tọa độ. Ở một khu dân cư mới, trên đường nông thôn hay trong một khu đất lớn chỉ có một số nhà, thứ trả về là địa chỉ đã biết gần nhất, và nó có thể là tòa nhà bên cạnh. Tọa độ vẫn là hồ sơ có giá trị quyết định.",
            ),
            h("Hoàn toàn không có vị trí"),
            steps(
              "Mở cài đặt điện thoại và tìm GeoCliks.",
              "Đặt quyền vị trí thành Khi dùng ứng dụng, hoặc Luôn luôn.",
              "Trên iPhone, hãy bật thêm Vị trí chính xác. Không có nó, bạn chỉ nhận được một khu vực thô thay vì một vị trí.",
              "Chụp lại. Các ảnh chụp trước đó không thể được gắn vị trí sau khi đã chụp.",
            ),
            h("Điểm dừng giao hàng nằm sai chỗ"),
            p(
              "Vị trí của một điểm dừng đến từ việc tra địa chỉ đã gõ, không phải từ một chiếc điện thoại. Hãy sửa địa chỉ rồi tra lại, hoặc đặt ghim thủ công.",
            ),
            warn(
              "Không thể thêm hay sửa vị trí sau khi chụp. Chính điều đó làm nó thành bằng chứng — nếu có thể sửa về sau, nó sẽ chẳng chứng minh được gì.",
            ),
            see("delivery-routes/geocoding-and-fixing-addresses", "verify/verify-results-explained"),
          ],
        },
      ],
    },
    {
      title: "Truy cập",
      articles: [
        {
          slug: "cant-sign-in",
          title: "Không đăng nhập được",
          summary: "Sai mật khẩu, email chưa xác nhận, hoặc sai cách đăng nhập.",
          keywords: [
            "đăng nhập",
            "mật khẩu",
            "đặt lại",
            "xác nhận",
            "khóa",
            "sign in",
            "login",
            "password",
            "reset",
            "verify",
            "google",
            "locked",
          ],
          body: [
            p("Hãy làm lần lượt theo thứ tự — nguyên nhân thường nằm ở một trong ba mục đầu."),
            h("Kiểm tra những điều cơ bản"),
            steps(
              "Xác nhận địa chỉ email. Một địa chỉ công việc và một địa chỉ cá nhân là hai tài khoản khác nhau.",
              "Dùng đúng cách bạn đã đăng ký. Một tài khoản tạo bằng Google thì không có mật khẩu để gõ.",
              "Hãy đặt lại mật khẩu từ màn hình đăng nhập nếu bạn không chắc.",
              "Hãy mở email xác nhận nếu bạn chưa bao giờ xác nhận địa chỉ — một tài khoản chưa xác nhận thì không đăng nhập được.",
            ),
            h("Không nhận được gì khi yêu cầu đặt lại mật khẩu"),
            ul(
              "Hãy kiểm tra thư rác.",
              "Chờ hai phút. Yêu cầu liên tục có thể bị giới hạn tần suất, khiến mọi thứ còn chậm hơn.",
              "Xác nhận địa chỉ đó có tồn tại — một yêu cầu đặt lại cho địa chỉ không có tài khoản sẽ không gửi gì cả.",
            ),
            h("Bạn bị yêu cầu chứng minh mình là người thật"),
            p(
              "Nhiều lần thử thất bại có thể kích hoạt một bài kiểm tra. Hãy hoàn thành nó rồi tiếp tục. Nếu nó cứ hiện lại, hãy thử một cửa sổ trình duyệt bình thường thay vì cửa sổ ẩn danh, và tắt mọi tiện ích mở rộng chặn tập lệnh.",
            ),
            h("Bạn đăng nhập được nhưng vào nhầm chỗ"),
            ul(
              "Nếu bạn thuộc nhiều không gian làm việc, hãy chuyển không gian làm việc từ menu tài khoản.",
              "Một thành viên Field chỉ thấy các dự án được giao cho họ, nên một không gian làm việc trông trống rỗng thường có nghĩa là chưa được giao dự án nào — hãy hỏi một admin.",
            ),
            note(
              "Bị xóa khỏi một không gian làm việc không xóa tài khoản của bạn. Bạn vẫn đăng nhập được; chỉ là bạn sẽ không thấy không gian làm việc đó.",
            ),
            see("troubleshoot/two-factor-issues", "getting-started/create-your-account"),
          ],
        },
        {
          slug: "two-factor-issues",
          title: "Sự cố xác thực hai lớp",
          summary: "Mã bị từ chối, mất điện thoại, và mã dự phòng hoạt động ra sao.",
          keywords: [
            "hai lớp",
            "xác thực hai lớp",
            "ứng dụng xác thực",
            "mã dự phòng",
            "mã bị từ chối",
            "2fa",
            "two factor",
            "totp",
            "authenticator",
            "backup codes",
            "code rejected",
          ],
          body: [
            p(
              "Xác thực hai lớp là tùy chọn và được cung cấp cho chủ sở hữu và admin từ trang hồ sơ của bạn. Đội ngoài hiện trường cố ý không bị bắt dùng ứng dụng xác thực, vì một chiếc điện thoại dùng chung trên xe tải sẽ khiến việc đó rất khổ sở.",
            ),
            h("Mã bị từ chối"),
            steps(
              "Kiểm tra bạn đang đọc mục GeoCliks trong ứng dụng xác thực, không phải một dịch vụ khác.",
              "Chờ mã tiếp theo. Mã đổi mỗi 30 giây và một mã sắp hết hạn thường bị từ chối.",
              "Gõ đủ sáu chữ số, không có dấu cách.",
              "Kiểm tra đồng hồ điện thoại đặt ở chế độ tự động. Một đồng hồ thiết bị lệch vài phút sẽ sinh ra mã mà máy chủ không chấp nhận.",
            ),
            h("Bạn làm mất chiếc điện thoại có ứng dụng xác thực"),
            p(
              "Hãy dùng một trong các mã dự phòng bạn được cấp khi bật xác thực hai lớp. Chọn tùy chọn mã dự phòng ở màn hình bước hai và nhập một mã. Mỗi mã chỉ dùng được một lần.",
            ),
            warn(
              "Nếu bạn mất cả ứng dụng xác thực lẫn mã dự phòng, chúng tôi không thể khôi phục tài khoản từ màn hình đăng nhập. Hãy gửi email tới support@geocliks.com từ chính địa chỉ của tài khoản và chuẩn bị cho việc kiểm tra danh tính — sự phiền phức đó chính là mục đích của xác thực hai lớp.",
            ),
            h("Tắt tính năng này"),
            p(
              "Hãy đăng nhập, mở hồ sơ của bạn và tắt xác thực hai lớp. Bạn sẽ được hỏi để xác nhận. Nếu bạn là chủ sở hữu, hãy cân nhắc để bật — đó là tài khoản có thể thay đổi thanh toán và xóa người khác.",
            ),
            note(
              "Xác thực hai lớp áp dụng cho tài khoản của bạn ở mọi nơi. Khi đã bật, cả trang web lẫn ứng dụng điện thoại đều hỏi bước thứ hai.",
            ),
            see("troubleshoot/cant-sign-in", "teamspace/roles-and-permissions"),
          ],
        },
        {
          slug: "invite-not-working",
          title: "Một lời mời không hoạt động",
          summary: "Không có email, liên kết hết hạn, hoặc gói đã hết chỗ ngồi.",
          keywords: [
            "mời",
            "lời mời",
            "chỗ ngồi",
            "hết hạn",
            "chấp nhận",
            "invite",
            "invitation",
            "seat",
            "expired",
            "accept",
            "qr",
            "email",
          ],
          body: [
            p("Vấn đề với lời mời quy về địa chỉ, chỗ ngồi, hoặc gói."),
            h("Họ chưa bao giờ nhận được email"),
            steps(
              "Mở Nhóm và kiểm tra danh sách đang chờ — nếu lời mời có ở đó thì nó đã được tạo.",
              "Kiểm tra địa chỉ xem có gõ nhầm không. Một lời mời gắn với đúng địa chỉ nó được gửi tới.",
              "Nhờ họ kiểm tra thư rác.",
              "Dùng mã QR thay thế: mở lời mời đang chờ, hiện mã lên, và nhờ họ quét bằng điện thoại.",
            ),
            h("Họ đã chấp nhận nhưng không thấy gì cả"),
            p(
              "Thành viên Field chỉ thấy các dự án họ được giao. Hãy giao dự án cho họ từ Nhóm, hoặc từ chính dự án đó, và nó sẽ hiện trên điện thoại của họ sau chốc lát.",
            ),
            h("Bạn hoàn toàn không gửi được lời mời"),
            ul(
              "Hết chỗ ngồi: lời mời đang chờ cũng chiếm một chỗ. Hãy thu hồi các lời mời cũ, xóa những người đã rời đi, hoặc lên gói cao hơn.",
              "Không có không gian nhóm: lời mời bắt đầu từ gói Business. Free và Plus chỉ có một chỗ ngồi.",
              "Sai vai trò: mời người khác cần vai trò admin hoặc chủ sở hữu.",
            ),
            h("Họ chấp nhận bằng một email khác"),
            p(
              "Cách đó không được — lời mời chỉ khớp với địa chỉ nó được gửi tới. Hãy thu hồi nó và gửi một lời mời mới tới địa chỉ họ thực sự dùng.",
            ),
            note("Thu hồi một lời mời đang chờ sẽ giải phóng chỗ ngồi của nó ngay lập tức."),
            see("teamspace/invite-your-crew", "plans-billing/seats-and-billing"),
          ],
        },
      ],
    },
    {
      title: "Tuyến đường, xuất dữ liệu và cảnh báo",
      articles: [
        {
          slug: "route-optimize-failed",
          title: "Một tuyến đường không tối ưu được",
          summary: "Thường là do địa chỉ chưa tra được. Đôi khi là do gói.",
          keywords: [
            "tối ưu",
            "tuyến đường",
            "thất bại",
            "tọa độ",
            "tra địa chỉ",
            "thứ tự",
            "optimize",
            "route",
            "failed",
            "coordinates",
            "geocode",
            "order",
          ],
          body: [
            p("Bộ tối ưu làm việc trên các vị trí bản đồ, không phải trên địa chỉ đã gõ."),
            h("\"Chưa điểm dừng nào có tọa độ\""),
            steps(
              "Mở tuyến đường và chọn Tra địa chỉ.",
              "Xem những điểm dừng tra không ra.",
              "Sửa phần chữ của địa chỉ, hoặc đặt ghim thủ công trên bản đồ.",
              "Tối ưu lại.",
            ),
            h("Tối ưu chạy được, nhưng vài điểm dừng bị kẹt ở cuối"),
            p(
              "Các điểm dừng không có vị trí thì không sắp thứ tự được, nên chúng được để ở cuối danh sách thay vì bị loại khỏi tuyến. Hãy tra địa chỉ hoặc đặt ghim cho chúng rồi tối ưu lại.",
            ),
            h("Bạn chọn tối ưu thông minh nhưng nhận được bộ tối ưu tiêu chuẩn"),
            p(
              "Trên một gói không có tối ưu thông minh, GeoCliks chạy bộ tiêu chuẩn thay vì từ chối. Bạn vẫn có một tuyến đã được sắp thứ tự. Lịch sử của tuyến ghi lại bộ tối ưu nào đã chạy.",
            ),
            h("Bạn vẫn thấy thứ tự có vẻ sai"),
            ul(
              "Hãy kiểm tra đã đặt địa chỉ xuất phát chưa, và có nên bật quay về kho không.",
              "Hãy kiểm tra thời gian phục vụ — một giá trị sai lệch quá đáng sẽ làm méo mọi ước tính giờ đến.",
              "Khung giờ trên các điểm dừng ràng buộc thứ tự, và một khung giờ chặt sẽ lấn át quãng đường ngắn nhất.",
              "Hãy kéo thả các điểm dừng bằng tay. Hiểu biết địa phương thắng thuật toán thường xuyên hơn các nhà cung cấp chịu thừa nhận.",
            ),
            see("delivery-routes/optimize-stop-order", "delivery-routes/geocoding-and-fixing-addresses"),
          ],
        },
        {
          slug: "export-or-report-failed",
          title: "Một lần xuất dữ liệu hoặc báo cáo bị lỗi",
          summary: "Giới hạn của gói, lựa chọn quá lớn, và các định dạng không được bao gồm.",
          keywords: [
            "xuất dữ liệu",
            "báo cáo",
            "thất bại",
            "tải xuống",
            "export",
            "report",
            "pdf",
            "excel",
            "zip",
            "kmz",
            "failed",
            "download",
          ],
          body: [
            p("Phần lớn các lần xuất dữ liệu thất bại là do giới hạn của gói chứ không phải do lỗi."),
            h("Định dạng không khả dụng"),
            ul(
              "Gói Free chỉ tạo ra PDF, tối đa 20 ảnh.",
              "Excel, ZIP và KMZ bắt đầu từ Plus.",
              "Bạn được báo trước khi tệp được dựng chứ không phải sau, nên không có gì bị tạo dở dang.",
            ),
            h("Bản xuất rất lớn"),
            steps(
              "Thu hẹp lựa chọn bằng bộ lọc ngày hoặc dự án.",
              "Xuất theo từng đợt — mỗi lần một tháng thì vừa dễ gửi email vừa dễ dựng hơn.",
              "Với hàng nghìn ảnh gốc, hãy chọn ZIP thay vì PDF. Một tệp PDF cỡ đó dù sao cũng không dùng được.",
            ),
            h("Tệp không bao giờ tải xuống"),
            ul(
              "Báo cáo được dựng trên máy chủ rồi được liệt kê trong danh sách báo cáo của bạn — hãy xem ở đó và tải lại thay vì dựng lại.",
              "Hãy kiểm tra trình duyệt không chặn tải xuống, và tìm trong thư mục tải về của bạn.",
              "Hãy thử một trình duyệt khác một lần trước khi báo lỗi.",
            ),
            h("Một tệp KMZ không mở được"),
            p(
              "KMZ cần Google Earth hoặc phần mềm GIS. Nó không phải định dạng tài liệu và sẽ không mở được bằng trình đọc PDF hay bảng tính.",
            ),
            note(
              "Mọi báo cáo đã tạo đều nằm lại trong danh sách báo cáo của bạn, nên bạn có thể tải lại về sau mà không cần dựng lại.",
            ),
            see("teamspace/reports-and-exports", "plans-billing/compare-plans"),
          ],
        },
        {
          slug: "notifications-not-arriving",
          title: "Thông báo không tới nơi",
          summary: "Thông báo đẩy trên điện thoại, và các email mà người nhận hàng đáng lẽ phải nhận được.",
          keywords: [
            "thông báo",
            "cảnh báo",
            "im lặng",
            "người nhận",
            "theo dõi",
            "notifications",
            "push",
            "email",
            "alerts",
            "silent",
            "recipient",
            "tracking",
          ],
          body: [
            p("Đây là hai hệ thống khác nhau, nên hãy kiểm tra đúng cái tương ứng với thứ đang thiếu."),
            h("Thông báo đẩy trên điện thoại"),
            steps(
              "Mở cài đặt điện thoại, tìm GeoCliks, và cho phép thông báo.",
              "Hãy kiểm tra chế độ Không làm phiền, chế độ Tập trung và mọi lịch giờ ngủ.",
              "Hãy mở ứng dụng một lần khi đang đăng nhập — thiết bị đăng ký nhận thông báo đẩy lúc đăng nhập, nên một chiếc điện thoại chưa mở ứng dụng lần nào kể từ khi cài lại thì chưa được đăng ký.",
              "Hãy tự gửi cho mình một tin nhắn từ ứng dụng web để thử.",
            ),
            h("Một thành viên đội không nhận được gì"),
            ul(
              "Họ phải là thành viên của không gian làm việc và đang đăng nhập trên thiết bị đó.",
              "Thông báo chung gửi tới các liên hệ của không gian làm việc — ai bị xóa khỏi không gian làm việc sẽ ngừng nhận được.",
              "Một chiếc điện thoại ngoại tuyến nhiều ngày sẽ nhận các thông báo còn trong hàng chờ khi kết nối lại, hoặc không nhận gì cả nếu chúng đã hết hạn.",
            ),
            h("Người nhận hàng không nhận được email"),
            ul(
              "Điểm dừng cần có địa chỉ email của người nhận. Không có nó thì không thể gửi email.",
              "Cài đặt thông báo của chính tuyến đường điều khiển email báo trước và email chứng từ giao hàng.",
              "Các điểm dừng thất bại không bao giờ gửi email chứng từ giao hàng — đó là chủ ý. Văn phòng xử lý những trường hợp đó bằng tay.",
              "Mỗi người nhận chỉ nhận mỗi email một lần, nên gửi lại sẽ không đi ra hai lần.",
              "Việc gửi email phải được thiết lập cho không gian làm việc của bạn. Nếu chưa người nhận nào trên bất kỳ tuyến nào từng nhận được gì, thì đó là thứ cần kiểm tra đầu tiên.",
            ),
            warn(
              "Hãy nhờ người nhận kiểm tra thư rác trước khi bạn kết luận rằng không có gì được gửi đi. Email giao dịch có kèm ảnh rơi vào hộp thư rác thường xuyên hơn bạn mong muốn.",
            ),
            see("delivery-routes/tracking-links-and-notifications", "teamspace/messages-and-broadcasts"),
          ],
        },
      ],
    },
  ],
};
