import { Link } from "wouter";
import {
  Building2,
  Clock,
  Earth,
  FileArchive,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  FolderTree,
  HardHat,
  MapPin,
  NotebookPen,
  SearchCheck,
  ShieldCheck,
  Signpost,
} from "lucide-react";
import {
  LandingCards,
  LandingCta,
  LandingFaq,
  LandingPage,
  LandingSection,
} from "../components/landing-page";
import { pageFaq } from "../lib/page-schema";
import { useLocale, type TKey } from "../lib/i18n";

/**
 * Search landing page for "construction photo log" and its neighbours ("as-built
 * photo report", "closeout photo package", "jobsite photo log template").
 *
 * The six row fields and four formats are read straight off `api/lib/exports.ts`:
 * the Excel "Photo log" sheet columns, the ZIP's originals + `manifest.csv` +
 * README, the KMZ pins, and the PDF's letterhead cover, capture map and
 * per-photo metadata block. Plan gating (Free: PDF up to 20 photos; Plus and up:
 * every format, comparison layouts, logo, share links) follows `api/lib/plans.ts`
 * — re-read both when either changes.
 */

const ROWS: { icon: typeof Clock; title: TKey; body: TKey }[] = [
  { icon: Clock, title: "cpl.row1.title", body: "cpl.row1.body" },
  { icon: MapPin, title: "cpl.row2.title", body: "cpl.row2.body" },
  { icon: Signpost, title: "cpl.row3.title", body: "cpl.row3.body" },
  { icon: Fingerprint, title: "cpl.row4.title", body: "cpl.row4.body" },
  { icon: FolderTree, title: "cpl.row5.title", body: "cpl.row5.body" },
  { icon: NotebookPen, title: "cpl.row6.title", body: "cpl.row6.body" },
];

/** The format names are product names, the same in every language. */
const FORMATS: { name: string; icon: typeof Clock; title: TKey; body: TKey }[] = [
  { name: "PDF", icon: FileText, title: "cpl.fmt1.title", body: "cpl.fmt1.body" },
  { name: "XLSX", icon: FileSpreadsheet, title: "cpl.fmt2.title", body: "cpl.fmt2.body" },
  { name: "ZIP", icon: FileArchive, title: "cpl.fmt3.title", body: "cpl.fmt3.body" },
  { name: "KMZ", icon: Earth, title: "cpl.fmt4.title", body: "cpl.fmt4.body" },
];

const WHO: { icon: typeof Clock; title: TKey; body: TKey }[] = [
  { icon: HardHat, title: "cpl.who1.title", body: "cpl.who1.body" },
  { icon: Building2, title: "cpl.who2.title", body: "cpl.who2.body" },
  { icon: SearchCheck, title: "cpl.who3.title", body: "cpl.who3.body" },
  { icon: ShieldCheck, title: "cpl.who4.title", body: "cpl.who4.body" },
];

/** The home page's sample manifest, verbatim. Not translated: it is what the report prints. */
const MANIFEST = [
  "Maple Grove Roof Replacement — 42 photos",
  "Verified 42 / 42 · Located 42 / 42",
  "Generated by GeoCliks · sealed SHA-256",
];

const linkClass =
  "font-semibold text-amber-ink underline decoration-amber/40 underline-offset-4 hover:decoration-amber";

function Grid2({ items }: { items: { icon: typeof Clock; title: string; body: string; tag?: string }[] }) {
  return (
    <div className="grid gap-6 sm:grid-cols-2">
      {items.map((item) => (
        <div key={item.title} className="rounded-[12px] border border-line bg-ink-2 p-5">
          <div className="flex items-center gap-2.5">
            <item.icon className="size-4.5 text-amber-ink" />
            {item.tag ? (
              <span className="mono text-[11px] font-bold tracking-widest text-amber-ink">{item.tag}</span>
            ) : null}
          </div>
          <h3 className="mt-3 font-display text-[15px] font-semibold text-chalk">{item.title}</h3>
          <p className="mt-1.5 text-[13.5px] leading-relaxed text-fog">{item.body}</p>
        </div>
      ))}
    </div>
  );
}

export default function ConstructionPhotoLog() {
  const { t, locale } = useLocale();
  const faq = pageFaq("/construction-photo-log", locale);
  const cards = (list: typeof ROWS) =>
    list.map((card) => ({ icon: card.icon, title: t(card.title), body: t(card.body) }));

  return (
    <LandingPage
      path="/construction-photo-log"
      eyebrow={t("cpl.eyebrow")}
      h1={t("cpl.h1")}
      sub={t("cpl.sub")}
    >
      <LandingSection label={t("cpl.s1.label")} h2={t("cpl.s1.h2")} intro={t("cpl.s1.intro")} />

      <LandingSection label={t("cpl.s2.label")} h2={t("cpl.s2.h2")}>
        <LandingCards items={cards(ROWS)} />
      </LandingSection>

      <LandingSection label={t("cpl.s3.label")} h2={t("cpl.s3.h2")} intro={t("cpl.s3.intro")} />

      <LandingSection label={t("cpl.s4.label")} h2={t("cpl.s4.h2")}>
        <Grid2
          items={FORMATS.map((f) => ({ icon: f.icon, tag: f.name, title: t(f.title), body: t(f.body) }))}
        />
      </LandingSection>

      <LandingSection label={t("cpl.s5.label")} h2={t("cpl.s5.h2")}>
        <Grid2 items={cards(WHO)} />
      </LandingSection>

      <LandingSection label={t("cpl.s6.label")} h2={t("cpl.s6.h2")} intro={t("cpl.s6.intro")}>
        <figure className="max-w-[640px] rounded-[12px] border border-line bg-ink-2 p-5 sm:p-6">
          <div dir="ltr" className="mono space-y-1.5 text-[13px] text-chalk sm:text-[14px]">
            {MANIFEST.map((line) => (
              <p key={line}>{line}</p>
            ))}
          </div>
          <figcaption className="mt-4 text-[13px] leading-relaxed text-fog">
            {t("cpl.s6.caption")}
          </figcaption>
        </figure>
      </LandingSection>

      <LandingSection label={t("cpl.faq.label")} h2={t("cpl.faq.h2")}>
        <LandingFaq entries={faq} />
      </LandingSection>

      <LandingCta
        h2={t("cpl.cta.h2")}
        body={t("cpl.cta.body")}
        primary={{ label: t("cpl.cta.primary"), to: "/get-app" }}
        secondary={{ label: t("cpl.cta.secondary"), to: "/pricing" }}
      />

      <section className="border-b border-line">
        <div className="mx-auto max-w-[1180px] px-5 py-10">
          <p className="text-[13.5px] leading-relaxed text-fog">
            {t("cpl.related.lead")}{" "}
            <Link to="/construction-photo-documentation" className={linkClass}>
              {t("cpl.related.construction")}
            </Link>
            {t("cpl.related.mid")}{" "}
            <Link to="/prove-crew-was-on-site" className={linkClass}>
              {t("cpl.related.onSite")}
            </Link>
            {t("cpl.related.join")}{" "}
            <Link to="/verify" className={linkClass}>
              {t("cpl.related.verify")}
            </Link>
            .
          </p>
        </div>
      </section>
    </LandingPage>
  );
}
