/**
 * Writes public/sitemap.xml from the routes that are actually public.
 *
 * The Help Center lives in the code catalog under src/web/help/content, so the
 * article URLs are generated rather than hand-maintained — a new article file
 * ships with its sitemap entry, and a deleted one cannot leave a 404 behind.
 *
 *   cd packages/web && bun scripts/gen-sitemap.ts
 *
 * Field Notes (/blog) is generated the same way, from the post catalog in
 * src/web/lib/posts — the blog is a folder of this site, not a subdomain, so it
 * belongs in this one sitemap rather than a second one.
 *
 * Deliberately omitted:
 *  - `changefreq` and `priority`: Google has said for years that it ignores
 *    both. They are noise that has to be kept plausible for no benefit.
 *  - `lastmod` on the marketing and Help URLs: only worth sending when it is
 *    truthful. Stamping every URL with today's date on each run is the thing
 *    Google learned to distrust, and the real per-page modification date is not
 *    knowable from here. Blog posts are the exception: each one carries its own
 *    `publishedAt`/`updatedAt` in the catalog, so that date is real and is sent.
 *
 * `hreflang` IS sent, but only for the paths in `LOCALIZED_PATHS` — the pages
 * that genuinely serve translated copy. Each of those is listed once per locale
 * with the full reciprocal `xhtml:link` set, which is the form Google requires
 * before it will honour any of it. Everything else is a single English URL with
 * no alternates, because eleven URLs of identical English text is duplicate
 * content rather than internationalization.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { allArticles, articleHref, helpCategories } from "../src/web/help/resolve";
import { posts, assertPostSeo } from "../src/web/lib/posts";
import { SITE_URL } from "../src/web/lib/seo-routes";
import {
  alternatesFor,
  isLocalizedPath,
  localizedPath,
  splitLocalePath,
} from "../src/web/lib/locale-url";
import { LOCALES } from "../src/api/lib/locales";

/** Public, indexable, static paths. Anything behind auth or a token is excluded. */
const STATIC_PATHS = [
  "/",
  "/get-app",
  "/help",
  "/pricing",
  "/construction-photo-documentation",
  "/proof-of-delivery",
  "/gps-timestamp-camera",
  "/roofing-photo-documentation",
  "/hvac-photo-documentation",
  "/property-inspection-photos",
  "/alternatives/companycam",
  "/alternatives/timemark",
  "/about",
  "/blog",
  "/blog/method",
  "/terms",
  "/privacy",
];

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function build(): string {
  // Fails the build rather than the crawl: a post with no SEO row would be
  // listed here and then serve the sitewide default title.
  assertPostSeo();

  const categories = helpCategories("en").map((category) => `/help/${category.slug}`);
  const articles = allArticles("en").map(({ category, article }) =>
    articleHref(category.slug, article.slug),
  );

  const entries: { path: string; lastmod?: string }[] = [
    // A translated path contributes every locale's URL; the rest contribute one.
    ...STATIC_PATHS.flatMap((p) =>
      isLocalizedPath(p)
        ? LOCALES.map((locale) => ({ path: localizedPath(p, locale.code) }))
        : [{ path: p }],
    ),
    ...categories.map((p) => ({ path: p })),
    ...articles.map((p) => ({ path: p })),
    ...posts.map((post) => ({
      path: `/blog/${post.slug}`,
      lastmod: post.updatedAt ?? post.publishedAt,
    })),
  ];

  const seen = new Set<string>();
  const unique = entries.filter((e) => !seen.has(e.path) && seen.add(e.path));

  const urls = unique
    .map((e) => {
      const loc = `    <loc>${xmlEscape(`${SITE_URL}${e.path}`)}</loc>`;
      const mod = e.lastmod ? `\n    <lastmod>${xmlEscape(e.lastmod)}</lastmod>` : "";
      // Every URL in a translated cluster carries the same full alternate set,
      // itself included. `alternatesFor` is empty for everything else.
      const alternates = alternatesFor(splitLocalePath(e.path).path)
        .map(
          (a) =>
            `\n    <xhtml:link rel="alternate" hreflang="${xmlEscape(a.hreflang)}" href="${xmlEscape(
              `${SITE_URL}${a.path}`,
            )}" />`,
        )
        .join("");
      return `  <url>\n${loc}${mod}${alternates}\n  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls}
</urlset>
`;
}

const out = path.join(import.meta.dirname, "..", "public", "sitemap.xml");
const xml = build();
await fs.writeFile(out, xml, "utf8");

const count = (xml.match(/<loc>/g) ?? []).length;
console.log(`sitemap.xml — ${count} URLs -> ${path.relative(process.cwd(), out)}`);
