/**
 * Regenerates the root `autumn.config.ts` from the `plans` table, so the operator console stays the
 * single place where plans are edited.
 *
 * Run from the repo root:  bun run autumn:config
 * Then push to Autumn:     bunx atmn push -y
 *
 * The DB row is the source of truth for what the app shows and enforces; Autumn owns what Stripe
 * actually charges, which is why the config has to be regenerated and pushed after a price change.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadPlans } from "../src/api/lib/plans";

const OUT = resolve(import.meta.dirname, "../../../autumn.config.ts");

function ident(id: string) {
  const camel = id.replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase());
  return /^[a-zA-Z_]/.test(camel) ? camel : `plan${camel}`;
}

const plans = await loadPlans();
// Enterprise (and anything priced "custom") is a sales conversation, not a checkout.
const billable = plans.filter((p) => p.priceCents >= 0 && p.autumnPlanId);

const lines: string[] = [
  "// GENERATED by packages/web/scripts/gen-autumn-config.ts — edit plans in /admin/plans, then run",
  "//   bun run autumn:config && bunx atmn push -y",
  'import { feature, plan, item } from "atmn";',
  "",
  'export const photos = feature({ id: "photos", name: "Photos", type: "metered", consumable: true });',
  'export const teamspace = feature({ id: "teamspace", name: "Teamspace", type: "boolean" });',
  'export const shareLinks = feature({ id: "share_links", name: "Share links", type: "boolean" });',
  'export const branding = feature({ id: "branding", name: "Custom branding", type: "boolean" });',
  'export const roles = feature({ id: "roles", name: "Role-based permissions", type: "boolean" });',
  "",
];

for (const p of billable) {
  const items: string[] = [];
  if (p.limits.photosPerMonth >= 0) {
    items.push(
      `    item({ featureId: photos.id, included: ${p.limits.photosPerMonth}, reset: { interval: "month" } }),`,
    );
  }
  if (p.limits.teamspace) items.push("    item({ featureId: teamspace.id }),");
  if (p.limits.shareLinks) items.push("    item({ featureId: shareLinks.id }),");
  if (p.limits.branding) items.push("    item({ featureId: branding.id }),");
  if (p.limits.roles) items.push("    item({ featureId: roles.id }),");

  lines.push(
    `export const ${ident(p.autumnPlanId as string)} = plan({`,
    `  id: ${JSON.stringify(p.autumnPlanId)},`,
    `  name: ${JSON.stringify(p.name)},`,
    ...(p.priceCents === 0
      ? // No `autoEnable` on the free plan: the Autumn account already has another default
        // product, and the app treats "no subscription" as free anyway.
        []
      : // Autumn's `amount` is in whole currency units (dollars), not cents.
        [`  price: { amount: ${p.priceCents / 100}, interval: "month" },`]),
    "  items: [",
    ...items,
    "  ],",
    "});",
    "",
  );
}

// Legacy passthrough: `time_stamp` existed in Autumn before this app owned the config, and the
// first generated push deleted it. It is re-emitted here (free, no items, not auto-enabled) purely
// so old external references to the product id resolve again. The app never reads it — no plan row
// points at it. If the original price/features are known, add them here, not in the plans table.
lines.push(
  "export const timeStamp = plan({",
  '  id: "time_stamp",',
  '  name: "Time Stamp (legacy)",',
  "  items: [],",
  "});",
  "",
);

const planIdents = billable.map((p) => ident(p.autumnPlanId as string)).join(", ");
lines.push(
  "export default {",
  "  features: [photos, teamspace, shareLinks, branding, roles],",
  `  plans: [${planIdents}, timeStamp],`,
  "};",
  "",
);

writeFileSync(OUT, lines.join("\n"));
console.log(`wrote ${OUT}\nplans: ${billable.map((p) => p.autumnPlanId).join(", ")}`);
