/**
 * Writes public/sitemap.xml from the routes that are actually public.
 *
 * The Help Center lives in the code catalog under src/web/help/content, so the
 * article URLs are generated rather than hand-maintained — a new article file
 * ships with its sitemap entry, and a deleted one cannot leave a 404 behind.
 *
 *   cd packages/web && bun scripts/gen-sitemap.ts
 *
 * Deliberately omitted:
 *  - `changefreq` and `priority`: Google has said for years that it ignores
 *    both. They are noise that has to be kept plausible for no benefit.
 *  - `lastmod`: only worth sending when it is truthful. Stamping every URL with
 *    today's date on each run is the thing Google learned to distrust, and the
 *    real per-page modification date is not knowable from here.
 *  - `hreflang`: the site serves all 11 locales from one URL with a client-side
 *    switch, so there is no per-locale URL to point at.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { allArticles, articleHref, helpCategories } from "../src/web/help/resolve";

const SITE_URL = "https://geocliks.com";

/** Public, indexable, static paths. Anything behind auth or a token is excluded. */
const STATIC_PATHS = [
  "/",
  "/get-app",
  "/help",
  "/construction-photo-documentation",
  "/alternatives/companycam",
  "/terms",
  "/privacy",
  // "/pricing" is intentionally absent: it redirects to /#pricing, so the home
  // page URL is the one that should carry the ranking signal.
];

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function build(): string {
  // The sitemap describes the English URL space, which is the whole URL space.
  const categories = helpCategories("en").map((category) => `/help/${category.slug}`);
  const articles = allArticles("en").map(({ category, article }) =>
    articleHref(category.slug, article.slug),
  );

  const paths = [...STATIC_PATHS, ...categories, ...articles];

  const seen = new Set<string>();
  const unique = paths.filter((p) => !seen.has(p) && seen.add(p));

  const urls = unique
    .map((p) => `  <url>\n    <loc>${xmlEscape(`${SITE_URL}${p}`)}</loc>\n  </url>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

const out = path.join(import.meta.dirname, "..", "public", "sitemap.xml");
const xml = build();
await fs.writeFile(out, xml, "utf8");

const count = (xml.match(/<loc>/g) ?? []).length;
console.log(`sitemap.xml — ${count} URLs -> ${path.relative(process.cwd(), out)}`);
