/**
 * Writes public/sitemap.xml from the routes that are actually public.
 *
 * The Help Center lives in the code catalog under src/web/help/content, so the
 * article URLs are generated rather than hand-maintained — a new article file
 * ships with its sitemap entry, and a deleted one cannot leave a 404 behind.
 *
 *   cd packages/web && bun scripts/gen-sitemap.ts
 *
 * Field Notes (/blog) is generated the same way, from the post catalog in
 * src/web/lib/posts — the blog is a folder of this site, not a subdomain, so it
 * belongs in this one sitemap rather than a second one.
 *
 * Deliberately omitted:
 *  - `changefreq` and `priority`: Google has said for years that it ignores
 *    both. They are noise that has to be kept plausible for no benefit.
 *  - `lastmod` on the marketing and Help URLs: only worth sending when it is
 *    truthful. Stamping every URL with today's date on each run is the thing
 *    Google learned to distrust, and the real per-page modification date is not
 *    knowable from here. Blog posts are the exception: each one carries its own
 *    `publishedAt`/`updatedAt` in the catalog, so that date is real and is sent.
 *  - `hreflang`: the site serves all 11 locales from one URL with a client-side
 *    switch, so there is no per-locale URL to point at.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { allArticles, articleHref, helpCategories } from "../src/web/help/resolve";
import { posts, assertPostSeo } from "../src/web/lib/posts";
import { SITE_URL } from "../src/web/lib/seo-routes";

/** Public, indexable, static paths. Anything behind auth or a token is excluded. */
const STATIC_PATHS = [
  "/",
  "/get-app",
  "/help",
  "/pricing",
  "/construction-photo-documentation",
  "/alternatives/companycam",
  "/blog",
  "/blog/method",
  "/terms",
  "/privacy",
];

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function build(): string {
  // Fails the build rather than the crawl: a post with no SEO row would be
  // listed here and then serve the sitewide default title.
  assertPostSeo();

  // The sitemap describes the English URL space, which is the whole URL space.
  const categories = helpCategories("en").map((category) => `/help/${category.slug}`);
  const articles = allArticles("en").map(({ category, article }) =>
    articleHref(category.slug, article.slug),
  );

  const entries: { path: string; lastmod?: string }[] = [
    ...STATIC_PATHS.map((p) => ({ path: p })),
    ...categories.map((p) => ({ path: p })),
    ...articles.map((p) => ({ path: p })),
    ...posts.map((post) => ({
      path: `/blog/${post.slug}`,
      lastmod: post.updatedAt ?? post.publishedAt,
    })),
  ];

  const seen = new Set<string>();
  const unique = entries.filter((e) => !seen.has(e.path) && seen.add(e.path));

  const urls = unique
    .map((e) => {
      const loc = `    <loc>${xmlEscape(`${SITE_URL}${e.path}`)}</loc>`;
      const mod = e.lastmod ? `\n    <lastmod>${xmlEscape(e.lastmod)}</lastmod>` : "";
      return `  <url>\n${loc}${mod}\n  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

const out = path.join(import.meta.dirname, "..", "public", "sitemap.xml");
const xml = build();
await fs.writeFile(out, xml, "utf8");

const count = (xml.match(/<loc>/g) ?? []).length;
console.log(`sitemap.xml — ${count} URLs -> ${path.relative(process.cwd(), out)}`);
